In [6]:
# part 1
# 1.constant or variable
# array
# matrix
# ragger
import tensorflow as tf
print(tf.Variable(12))
print(tf.Variable([12]))
print(tf.Variable([[12],[20]]))
print(tf.ragged.constant([[1],[1,2,3],[2,3,3,3]]))


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=12>
<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([12], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[12],
       [20]], dtype=int32)>
<tf.RaggedTensor [[1], [1, 2, 3], [2, 3, 3, 3]]>


In [26]:
2
# constant:we cant change the value of constant
# variable:we can change value of varible
a=tf.Variable([4.0, 5.0, 6.0])
b=tf.constant([4.0, 5.0, 6.0])
print("varible ",a.numpy())
print("constant ",b.numpy())
a.assign([1,2,3])
# b.assign([1,2,3]) this show error
print("after update",a.numpy())


varible  [4. 5. 6.]
constant  [4. 5. 6.]
after update [1. 2. 3.]


In [35]:
3
a=tf.Variable([[4.0, 5.0, 6.0],[1.0,2.0,3.0],[5.0,6.0,7.0]])
b=tf.Variable([[4.0, 5.0, 6.0],[1.0,2.0,3.0],[5.0,6.0,7.0]])
print("adding")
print((a+b).numpy())
print("mulitply")
print((a*b).numpy())
print("adding element wise value")
print((a+100).numpy())

adding
[[ 8. 10. 12.]
 [ 2.  4.  6.]
 [10. 12. 14.]]
mulitply
[[16. 25. 36.]
 [ 1.  4.  9.]
 [25. 36. 49.]]
adding element wise value
[[104. 105. 106.]
 [101. 102. 103.]
 [105. 106. 107.]]


In [39]:
# part 2
# task 1

# 1.
m1=tf.random.normal(shape=(3,3))
print(m1.numpy())

[[-0.24737406  0.50383997  0.6653851 ]
 [-1.3557824   0.39961785 -1.0892054 ]
 [-2.7510517   2.65965     1.2224432 ]]


In [43]:
2
m2=tf.random.normal(shape=(4,4),mean=0,stddev=1)
print(m2.numpy())

[[ 0.70483273  0.05082822 -0.80806255  2.0111516 ]
 [-2.0087128   0.8411125  -1.2360187   0.9469998 ]
 [-0.67002165  0.36468452  0.10030359 -1.9304497 ]
 [-0.9316629  -0.18576412  0.34941763  0.49249023]]


In [44]:
3.
m2=tf.random.normal(shape=(2,2),mean=3,stddev=.5)
print(m2.numpy())

[[3.4144738 2.0279326]
 [2.0838516 3.4357235]]


In [47]:
4.
a=tf.random.normal(shape=(4,4),mean=0,stddev=1)
b=tf.random.normal(shape=(4,4),mean=0,stddev=1)
d=a+b#matrix addition between matrix A and matrix B, and store the result in matrix Dc
print(d.numpy())


[[ 2.6366725   0.6313688  -0.48125064  1.5999981 ]
 [-0.11899608  0.37571248 -0.9261093   1.3834589 ]
 [-0.30220884 -0.9920263   1.7494477   2.3230615 ]
 [-0.81636244 -1.747408    1.0999268  -1.4295267 ]]


In [50]:
5.
c=tf.random.normal(shape=(4,4),mean=200,stddev=1)
d=tf.random.normal(shape=(4,4),mean=200,stddev=1)
e=c*d #matrix multiplication between matrix C and matrix D, and store the result in matrix E.
print(e.numpy())

[[40057.96  40698.85  39572.93  40331.29 ]
 [40341.582 39869.78  39602.76  40329.24 ]
 [40018.477 40015.64  39567.27  40320.973]
 [40029.195 40125.004 40393.203 40476.55 ]]


In [53]:
# tast2
1.
f=tf.random.uniform(shape=(3,3))#matrix F with dimensions 2x2,
print(f)

tf.Tensor(
[[0.65176606 0.8646059  0.9758409 ]
 [0.9345944  0.46657205 0.6658598 ]
 [0.21483779 0.27941287 0.08563685]], shape=(3, 3), dtype=float32)


In [54]:
2.
g=tf.transpose(f)#the transpose of matrix F and store the result in matrix Gc
print(g)

tf.Tensor(
[[0.65176606 0.9345944  0.21483779]
 [0.8646059  0.46657205 0.27941287]
 [0.9758409  0.6658598  0.08563685]], shape=(3, 3), dtype=float32)


In [56]:
3.
h=tf.exp(f)#the elementDwise exponential of matrix F and store the result in matrix Hc
print(h)

tf.Tensor(
[[1.9189268 2.3740702 2.6533976]
 [2.5461805 1.5945189 1.9461632]
 [1.2396607 1.3223532 1.0894107]], shape=(3, 3), dtype=float32)


In [61]:
4.
i=tf.concat([f,g],axis=1)#I by concatenating matrix F and matrix G horizontallyc
print(i)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0.65176606, 0.8646059 , 0.9758409 ],
       [0.9345944 , 0.46657205, 0.6658598 ],
       [0.21483779, 0.27941287, 0.08563685],
       [0.65176606, 0.9345944 , 0.21483779],
       [0.8646059 , 0.46657205, 0.27941287],
       [0.9758409 , 0.6658598 , 0.08563685]], dtype=float32)>

In [63]:
5.
j=tf.concat([f,g],axis=0)#J by concatenating matrix F and matrix H vertically.
print(j)

tf.Tensor(
[[0.65176606 0.8646059  0.9758409 ]
 [0.9345944  0.46657205 0.6658598 ]
 [0.21483779 0.27941287 0.08563685]
 [0.65176606 0.9345944  0.21483779]
 [0.8646059  0.46657205 0.27941287]
 [0.9758409  0.6658598  0.08563685]], shape=(6, 3), dtype=float32)
